# Windows styles
set-option -g status-style bg=colour235,fg=colour136,default
set-window-option -g window-status-style fg=colour244,bg=default,dim
set-window-option -g window-status-current-style bg=default,bright

# Panes styles
set-option -g pane-border-style fg=colour237
set-option -g pane-active-border-style fg=colour242 

# Status bar styles
set -g status-position bottom
set -g status-justify centre
set -g status-style 'fg=red'

set -g status-left ''
set -g status-left-length 100

set -g status-right-style 'fg=black bg=yellow'
set -g status-right '%Y-%m-%d %H:%M '
set -g status-right-length 50

setw -g window-status-current-style 'fg=black bg=red'
setw -g window-status-style 'fg=red bg=black'
setw -g window-status-bell-style 'fg=yellow bg=red bold'

# Mouse for resizing panes
set -g mouse on

# Base index & numbering
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# History limit
set-option -g history-limit 5000

# Key bindings

### Leader key
unbind C-b
unbind C-q
set -g prefix C-q
bind C-q send-prefix

### Reload config key
unbind r
bind r source-file ~/.tmux.conf
display-message "Reloaded configuration: ~/.tmux.conf"

### New window
unbind c
bind-key c command-prompt -p "Name of new window: " "new-window -n '%%' -c '#{pane_current_path}'"

### Clear screen
unbind C
bind C send-keys 'C-l'

### Move windows
bind -r "<" swap-window -d -t -1
bind -r ">" swap-window -d -t +1

### Split panes
unbind %
unbind '"'

bind | split-window -hc "#{pane_current_path}"  
bind-key "\\" split-window -h -c "#{pane_current_path}"      # Split horizontally
bind-key "|" split-window -fh -c "#{pane_current_path}"      # Global split horizontally

bind - split-window -vc "#{pane_current_path}"
bind-key "-" split-window -v -c "#{pane_current_path}"       # Split vertically
bind-key "_" split-window -fv -c "#{pane_current_path}"      # Global split vertically

bind-key + select-layout main-horizontal
bind-key = select-layout main-vertical

### Kill windows & panes
unbind C-7
unbind C-x
bind-key C-x kill-pane

# Vim motion
setw -g mode-keys vi
set -g status-keys vi
set-window-option -g mode-keys vi

### Resize pane
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

### Tmux Vim Navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|fzf|foobar)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'

tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

bind-key -T copy-mode-vi 'C-[' send-keys -X cancel # ESC
