# Windows styles
set-option -g status-style bg=colour235,fg=colour136,default
set-window-option -g window-status-style fg=colour244,bg=default,dim
set-window-option -g window-status-current-style bg=default,bright

# # Panes styles
# set-option -g pane-border-style fg=colour237
# set-option -g pane-active-border-style fg=colour242 #fg=base01

# # Status bar styles
# set -g status-interval 1
# set -g status-justify centre # center align window list
# set -g status-left-length 20
# set -g status-right-length 140
# set -g status-left '#[fg=green]#H #[fg=black]• #[fg=green,bright]#(uname -r | cut -c 1-6)#[default]'
# set -g status-right '#[fg=green,bg=default,bright]#(tmux-mem-cpu-load) #[fg=red,dim,bg=default]#(uptime | cut -f 4-5 -d " " | cut -f 1 -d ",") #[fg=white,bg=default]%a%l:%M:%S %p#[default] #[fg=blue]%Y-%m-%d'

# Key binding for reloading tmux configuration
unbind r
bind r source-file ~/.tmux.conf
display-message "Reloaded configuration: ~/.tmux.conf"

# Mouse for resizing panes
set -g mouse on

# Base index & numbering
set -g base-index 0
setw -g pane-base-index 0
set -g renumber-windows on
set-window-option -g automatic-rename

# History limit
set-option -g history-limit 5000

# Leader key
unbind C-b
unbind C-q
set -g prefix C-q
bind C-q send-prefix

# Key bindings

## New windows must have name
unbind c
bind-key c command-prompt -p "Name of new window: " "new-window -n '%%'"

### Move windows
bind -r "<" swap-window -d -t -1
bind -r ">" swap-window -d -t +1

### Split panes
unbind %
unbind '"'

bind | split-window -hc "#{pane_current_path}"  
bind-key "\\" split-window -h -c "#{pane_current_path}"      # Split horizontally
bind-key "|" split-window -fh -c "#{pane_current_path}"      # Global split horizontally

bind - split-window -vc "#{pane_current_path}"
bind-key "-" split-window -v -c "#{pane_current_path}"       # Split vertically
bind-key "_" split-window -fv -c "#{pane_current_path}"      # Global split vertically

### Kill windows & panes
# unbind C-7
# bind-key C-7 kill-window

unbind C-x
bind-key C-x kill-pane

# Vim mode
# setw -g mode-keys vi
# bind h select-pane -L
# bind j select-pane -D
# bind k select-pane -U
# bind l select-pane -R
# bind-key h select-pane -L
# bind-key j select-pane -D
# bind-key k select-pane -U
# bind-key l select-pane -R
# set-window-option -g mode-keys vi
# if-shell "test '\( #{$TMUX_VERSION_MAJOR} -eq 2 -a #{$TMUX_VERSION_MINOR} -ge 4 \)'" 'bind-key -Tcopy-mode-vi v send -X begin-selection; bind-key -Tcopy-mode-vi y send -X copy-selection-and-cancel'
# if-shell '\( #{$TMUX_VERSION_MAJOR} -eq 2 -a #{$TMUX_VERSION_MINOR} -lt 4\) -o #{$TMUX_VERSION_MAJOR} -le 1' 'bind-key -t vi-copy v begin-selection; bind-key -t vi-copy y copy-selection'

# Plugins
# ...
# Vim-Tmux Navigation
